name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.ref_name != 'main'
    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      run: make build
  
  build-and-push:
    
    name: Make build and push
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: make build

    - name: Upload
      run: make push
